version: 1.0.0.{build}
skip_tags: true
only_commits:
  files:
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cpp'
    - '**/*.pro'
    - '**/*.pri'
    - '**/*.qrc'
    - '**/*.ui'
    - '**/*.yml'
shallow_clone: true
matrix:
  fast_finish: true
image: Visual Studio 2017
init:
  - set "QTVER=5.9"
  - set "QTDIR=C:\Qt\%QTVER%\msvc2017_64"
  - set "QTAVID=7ddf6db"
  - call "%QTDIR%\bin\qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
install:
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - cd ci
  - if exist build rd /s /q build
  - md build
  - cd build
  - call ..\install.bat
  - powershell ..\patch.ps1
  - cd ..
  - rd /s /q build
  - call update_version.bat
  - cd ..
build_script:
  - call build.bat
test: off
artifacts:
  - path: .qmake.conf
deploy: off
