version: 1.0.0.{build}
skip_tags: true
only_commits:
  files:
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cpp'
    - '**/*.pro'
    - '**/*.pri'
    - '**/*.qrc'
    - '**/*.ui'
    - '**/*.yml'
matrix:
  fast_finish: true
  allow_failures:
    - platform: x64
      configuration: Release
image: Visual Studio 2017
platform: x64
configuration: Release
init:
  - git config --global core.autocrlf input
install:
  - git submodule update --init --recursive
  - md build
  - cd build
  - call "..\ci\install_dep.bat"
  - call "..\ci\update_version.bat"
  - cd..
build_script:
  - call "C:\Qt\5.11\msvc2017_64\bin\qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - call build.bat
#after_build:
  #- call "ci\prepare_deploy.bat"
test: off
#artifacts:
  #- path: dd-*.7z
#deploy:
  #provider: FTP
  #protocol: sftp
  #host: frs.sourceforge.net
  #username: wangwenx190
  #password:
    #secure: awR+dRiLYrwqcPDhhQC/uQ==
  #folder: /home/frs/project/d/dy/dynamic-desktop/beta
  #active_mode: false
artifacts:
  - path: version_ci.h
deploy: off
