version: 1.0.0.{build}
branches:
  only:
    - master
skip_tags: true
only_commits:
  files:
    - '**/*.h'
    - '**/*.hpp'
    - '**/*.cpp'
    - '**/*.pro'
    - '**/*.pri'
    - '**/*.qrc'
    - '**/*.ui'
    - '**/*.yml'
image: Visual Studio 2017
shallow_clone: true
matrix:
  fast_finish: true
  allow_failures:
    - platform: x64
      configuration: Release
  exclude:
    - platform: x86
    - configuration: Debug
platform: x64
configuration: Release
init:
  - set "CI=AppVeyor"
  - set "QTVER=5.9"
  - set "QTDIR=C:\Qt\%QTVER%\msvc2017_64"
  - set "QTAVID=7ddf6db"
  - call "%QTDIR%\bin\qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
install:
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - cd ci
  - if exist build rd /s /q build
  - md build
  - cd build
  - call ..\install.bat
  - powershell ..\patch.ps1
  - cd ..
  - rd /s /q build
  - cd ..
before_build:
  - echo DD_VERSION         = %APPVEYOR_BUILD_VERSION%>version_ci.pri
  - echo DD_COMMIT_ID       = %APPVEYOR_REPO_COMMIT%>>version_ci.pri
  - echo DD_COMMIT_TIME     = %APPVEYOR_REPO_COMMIT_TIMESTAMP%>>version_ci.pri
  - echo FFMPEG_VERSION_STR = 4.0.2-git>>version_ci.pri
build_script:
  - call build.bat
test: off
artifacts:
  - path: version_ci.pri
deploy: off
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
